language: java
script: mvn verify
dist: precise
jdk:
  - oraclejdk8

notifications:
  email:
    - serge@jkiss.org
    
cache:
  directories:
  - $HOME/.m2

before_install: 
 - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
 - mvn clean